theme: minima
title: Frontier of Ignorance
author: D. Howard
description: A web log of an architect doing computational design. May contain incomplete ideas and half-baked projects.

google_analytics: G-KZW07LY8QQ
